---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Java-deployment
spec:
  selector:
    matchLabels:
      app: Java
  replicas: 2
  template:
    metadata:
      labels:
        app: Java
    spec:
      containers:
      - name: Java
        image: bapathuashokreddy/javaproject
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.25"
            memory: "128Mi"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: Java-service
spec:
  selector:
    app: Java
  type: NordPort
  ports:
    - port: 8081
      targetPort: 8081
